name: Gradle Plugin CI

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Compile Plugin and check example
        working-directory: example
        # building the example also builds the plugin
        run: ./gradlew build
      - name: Login to Gradle Plugin Portal
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GRADLE_CONFIG: ${{ secrets.GRADLE_CONFIG }}
        run: echo "$GRADLE_CONFIG" > ~/.gradle/gradle.properties
      - name: Publish Plugin
        if: startsWith(github.ref, 'refs/tags/')
        env:
          MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew publish publishPlugins
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
