name: Gradle Plugin CI

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Compile Plugin and check example
        working-directory: example
        # building the example also builds the plugin
        run: ./gradlew build
      - name: Login to Gradle Plugin Portal
        if: github.ref == 'refs/heads/main'
        env:
          GRADLE_CONFIG: ${{ secrets.GRADLE_CONFIG }}
        run: echo "$GRADLE_CONFIG" > ~/.gradle/gradle.properties
      - name: Publish Plugin
        if: github.ref == 'refs/heads/main'
        env:
          MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew publish publishPlugins
